export const REQUESTING_SERVICE = 'REQUESTING_SERVICE';
export const LOCATION_AUTOCOMPLETE_SUCCESS = 'LOCATION_AUTOCOMPLETE_SUCCES';
export const LOCATION_SERVICE_FAIL = 'LOCATION_SERVICE_FAIL';
export const GEO_LOCATION_SUCCESS = 'GEO_LOCATION_SUCCES';
export const GEOCODING_SUCCESS = 'LOCATION_SEARCH_SUCCESS';
export const REVERSE_GEOCODING_SUCCESS = 'REVERSE_GEOCODING_SUCCESS';
export const CLEAR_SUGGESTIONS = 'CLEAR_SUGGESTIONS';


export const GET_FORECAST_SUCCESS = 'GET_FORECAST_SUCCESS';
export const GET_FORECAST_FAIL = 'GET_FORECAST_FAIL';
export const REQUESTING_FORECAST = 'REQUESTING_FORECAST';

export const CLEAR_ERROR = 'CLEAR_ERROR';